[project]
name = "esasrec"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "numpy>=1.24",
    "nvidia-ml-py>=12",
    "onnx>=1.21.0",
    "onnxruntime>=1.25.1",
    "onnxruntime-gpu>=1.25.1",
    "pandas>=2.0",
    "torch>=2.1",
    "tqdm>=4.66",
    "wandb>=0.17",
]

[tool.setuptools]
packages = ["esasrec"]

[tool.uv.sources]
torch = { index = "pytorch-cu124" }
causal-conv1d = { path = "causal_conv1d-1.5.0.post8+cu12torch2.6cxx11abiFALSE-cp311-cp311-linux_x86_64.whl" }
mamba-ssm = { path = "mamba_ssm-2.2.3+cu12torch2.6cxx11abiFALSE-cp311-cp311-linux_x86_64.whl" }

[[tool.uv.index]]
name = "pytorch-cu124"
url = "https://download.pytorch.org/whl/cu124"

[dependency-groups]
dev = [
    "ruff>=0.15.10",
]
mamba = [
    "causal-conv1d",
    "mamba-ssm",
]

# [tool.ruff]
# line-length = 130

[tool.ruff.lint]
fixable = ["ALL"]

ignore = [
    "ARG001", # allow passing and not using parameters (for authorization requrements)
    "ANN002", # allow missing annotation for *args
    "ANN003", # allow missing annotation for **kwargs
    "ANN201", # allow missing function return type annotation
    "N818", # do not enforce "Error" suffix for custom exceptions
    "N999", # do not enforce snake_case module names
    "RUF001", # do not warn about ambiguous characters in strings
    "RUF002", # do not warn about ambiguous characters in docstrings
    "FBT001", # boolean function parameters
    "FBT002", # default boolean parameters
    "F401", # imported but unused
]

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.lint.isort]
split-on-trailing-comma = false

[tool.ruff.format]
line-ending = "lf"
skip-magic-trailing-comma = true

